package app.cityxplore.core

import compose.project.demo.BuildConfig

/**
 * Android implementation of debug configuration.
 * Uses BuildConfig.DEBUG which is automatically generated by Android Gradle Plugin
 * based on the build type (debug = true, release = false).
 */
actual val isDebugBuild: Boolean = BuildConfig.DEBUG
