-- Migration: Insert sample POIs for testing

INSERT INTO points_of_interest (name,
                                description,
                                category,
                                location,
                                is_active,
                                is_major)
VALUES ('Historical POI 1',
        'Simple historical point of interest.',
        'HISTORICAL',
        ST_SetSRID(ST_MakePoint(20.991105, 52.097245), 4326)::geography,
        true,
        false),

       ('Cultural POI 1',
        'Simple cultural point of interest.',
        'CULTURAL',
        ST_SetSRID(ST_MakePoint(20.991340, 52.097180), 4326)::geography,
        true,
        false),

       ('Nature POI 1',
        'Simple nature point of interest.',
        'NATURE',
        ST_SetSRID(ST_MakePoint(20.991250, 52.097020), 4326)::geography,
        true,
        false),

       ('Food POI 1',
        'Simple food point of interest.',
        'FOOD',
        ST_SetSRID(ST_MakePoint(20.991415, 52.097255), 4326)::geography,
        true,
        false),

       ('Sports POI 1',
        'Simple sports point of interest.',
        'SPORTS',
        ST_SetSRID(ST_MakePoint(20.991060, 52.097090), 4326)::geography,
        true,
        false),

       ('Entertainment POI 1',
        'Simple entertainment point of interest.',
        'ENTERTAINMENT',
        ST_SetSRID(ST_MakePoint(20.991180, 52.097320), 4326)::geography,
        true,
        false),

       ('Custom POI 1',
        'Simple custom point of interest.',
        'CUSTOM',
        ST_SetSRID(ST_MakePoint(20.991325, 52.097115), 4326)::geography,
        true,
        false),

       ('Other POI 1',
        'Simple other point of interest.',
        'OTHER',
        ST_SetSRID(ST_MakePoint(20.991075, 52.097185), 4326)::geography,
        true,
        false),

       ('Unknown POI 1',
        'Simple unknown point of interest.',
        'UNKNOWN',
        ST_SetSRID(ST_MakePoint(20.991300, 52.097285), 4326)::geography,
        true,
        false),

       ('Historical POI Major 1',
        'Simple major historical point of interest.',
        'HISTORICAL',
        ST_SetSRID(ST_MakePoint(20.991210, 52.097210), 4326)::geography,
        true,
        true);
