services:
  cityxplore-postgres:
    image: postgis/postgis:18-3.6
    container_name: cityxplore-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cityxplore
      POSTGRES_PASSWORD: cityxplore
      POSTGRES_DB: cityxplore
    volumes:
      - pgdata_cityxplore:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  pgdata_cityxplore: