spring:
  application:
    name: cityxplore-backend-prod

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1

  datasource:
    url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    org.flywaydb.core: INFO
    org.hibernate.SQL: WARN